ifeq ($(TARGET_KERNEL_VERSION), 4.14)
AUDIO_KERNEL_ROOT := $(PWD)/kernel/msm-4.14/techpack/audio
$(shell mkdir -p $(PWD)/kernel/msm-4.14/techpack/audio)
$(shell cp -rf $(PWD)/vendor/qcom/opensource/audio-kernel/* \
$(AUDIO_KERNEL_ROOT))
$(shell rm -f $(AUDIO_KERNEL_ROOT)/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/include/uapi/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/soc/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/soc/Kbuild)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/dsp/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/dsp/Kbuild)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/dsp/codecs/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/dsp/codecs/Kbuild)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/ipc/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/ipc/Kbuild)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/asoc/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/asoc/Kbuild)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/asoc/codecs/Android.mk)
$(shell rm -f $(AUDIO_KERNEL_ROOT)/asoc/codecs/Kbuild)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/wcd934x)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/aqt1000)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/ep92)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/msm_sdw)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/wcd937x)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/csra66x0)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/bolero)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/wcd9360)
$(shell rm -rf $(AUDIO_KERNEL_ROOT)/asoc/codecs/sdm660_cdc)
$(shell cp -f $(AUDIO_KERNEL_ROOT)/Makefile.builtin $(AUDIO_KERNEL_ROOT)/Makefile)
$(shell mv -f $(AUDIO_KERNEL_ROOT)/asoc/Makefile.builtin $(AUDIO_KERNEL_ROOT)/asoc/Makefile)
$(shell mv -f $(AUDIO_KERNEL_ROOT)/soc/Makefile.builtin $(AUDIO_KERNEL_ROOT)/soc/Makefile)
$(shell mv -f $(AUDIO_KERNEL_ROOT)/ipc/Makefile.builtin $(AUDIO_KERNEL_ROOT)/ipc/Makefile)
$(shell mv -f $(AUDIO_KERNEL_ROOT)/dsp/Makefile.builtin $(AUDIO_KERNEL_ROOT)/dsp/Makefile)
$(shell mv -f $(AUDIO_KERNEL_ROOT)/asoc/codecs/Makefile.builtin $(AUDIO_KERNEL_ROOT)/asoc/codecs/Makefile)
$(shell mv -f $(AUDIO_KERNEL_ROOT)/dsp/codecs/Makefile.builtin $(AUDIO_KERNEL_ROOT)/dsp/codecs/Makefile)
$(shell sed -i 's/m/y/g' $(AUDIO_KERNEL_ROOT)/config/sa6155auto.conf)
$(shell sed -i '/is_snd_event_fwk_enabled/,+3d' $(AUDIO_KERNEL_ROOT)/include/soc/snd_event.h)
endif
